### ISSUE TITLE
CA review - comment #4

### ISSUE THREAD

**Issue by whitere123** [Malavika-Srinivasan/CAS741#10] opened 2018-10-08 23:55 UTC
This comment is regarding moving content into different subsections. 

#4 
- It might be more appropriate to have 5.1.1 , 5.1.2 and 5.1.3 in the terminology and definitions section. 
- you may also want to consider changing the order of 5.4 and 5.5. (ie make the goal statements section 5.5 and the GDs section 5.4). You might have to ask Dr. Smith about this adjustment..

**Comment by Malavika-Srinivasan** [comment] 2018-10-10 18:37
It might be more appropriate to have 5.1.1 , 5.1.2 and 5.1.3 in the terminology and definitions section. - Yes good idea. But, it kind of has a good flow from curve fitting helps to understand the relevance between curve fitting and regression, interpolation etc. I guess, we should ask for help from Dr.Smith @smiths  about moving them. My idea is to add them to terminologies and definition and also have them at "Background section", but that would be repeating information with no additional details.

**Comment by Malavika-Srinivasan** [comment] 2018-10-10 18:40
you may also want to consider changing the order of 5.4 and 5.5. (ie make the goal statements section 5.5 and the GDs section 5.4). You might have to ask Dr. Smith about this adjustment.. Yes Robert. Thats a good idea. But I had something different in my mind. I wanted it to be ordered like General definitions, Data definitions and then goals. I already got approval for that. But we both had the same point that all the definitions could be grouped together. Thanks for your idea.

**Comment by Malavika-Srinivasan** [comment] 2018-10-10 18:43
75e7983 - This commit addresses this feedback "you may also want to consider changing the order of 5.4 and 5.5. (ie make the goal statements section 5.5 and the GDs section 5.4). You might have to ask Dr. Smith about this adjustment.."

This issue is still open because I want to wait for Dr.Smith for the first feedback.

**Comment by smiths** [comment] 2018-10-12 10:43
@Malavika-Srinivasan, the way you include the text from @whitere123 in your comments is confusing.  I'm not quite able to parse the above.  Are you still waiting for feedback from me on something?

**Comment by Malavika-Srinivasan** [comment] 2018-10-12 15:51
@smiths 

Yes Dr.Smith. In my background section, I have the following info.

Curve fitting is the process of ...... A fit for the data can be obtained by different methods like interpolation, data smoothing and regression.

Interpolation: Interpolation is a process of fitting a function to given data so that the function has some values as the given data.

Smoothing: Smoothing is a process of creating an approximating function that attempts to capture important patterns in the data, while leaving out noise or other rapid phenomena.

Regression: Regression analysis is the process of finding the best fit parameters for a regression model for a given set of data points and thus obtain a curve through a set of data points.

Robert thinks it would be good to move Regression, smoothing and interpolation to terminologies snd definition. But I like to have it in background section itself as I feel it gives a logical understanding that regression, interpolation etc are curve fitting methods. 

I can add them to terminologies and definitions too but just don't want to remove it from background. I also feel repeating the same info at same abstraction level is not useful. So, I asked for your feedback. Please help.

**Comment by smiths** [comment] 2018-10-16 20:58
@Malavika-Srinivasan, I know it wasn't part of your question, but you really should define interpolation as a fit where the fitting function passes exactly through the data points.  This is what distinguishes interpolation from regression.

As far as repeating the definitions twice, I don't like that idea.  Repetition isn't a good idea, unless as you say the repetition adds something that makes it less abstract.  I could see this information being presented either as you have done it, or as @whitere123 suggests.  I don't have a strong preference, so you can leave it as it is.

I haven't done the review of your documentation yet, but my initial thought is that the comparison between interpolation, regression and smoothing is a little terse.  To really distinguish them you will need more information, like what I mentioned above about the definition for interpolation.

**Comment by Malavika-Srinivasan** [comment] 2018-10-29 15:23
Closing this issue. Changed the definition of interpolation.


3f94a61

**Closed as completed** 2018-10-29 15:23 UTC
